
require('plugin_configs.bufferline')
require('plugin_configs.comment')
require('plugin_configs.cmp')
require('plugin_configs.debugger')
require('plugin_configs.lualine')
require('plugin_configs.mason-lsp')
require('plugin_configs.vscode')
require('plugin_configs.telescope')
require('plugin_configs.treesitter')
